\encoding UTF8

INSERT INTO usuarios (nombre, email, password, rol) VALUES
('admin','admin@admin.com', '$2b$10$fKZgXe6y2fAOmPbbQ4XWt.WIbhMW0Dg15xzOhZ0m1Q1im4FvIF7uC','admin');

INSERT INTO usuarios (nombre, email, password) VALUES
('cliente','cliente@cliente.com', '$2b$10$uy6iwIOExIrCMQ4QBuT5au48lm9H7BNCzCUzB4E7.B/NZqwpCdaBS');

INSERT INTO productos (id_admin, titulo, descripcion, stock, tipo, 
url_imagen, url_imagen2, url_imagen3, url_imagen4, destacado, activo, precio) VALUES
(1,'Mancuernas Hexagonales 2x10 kg','Par de mancuernas de goma antideslizante.',15,'producto',
'producto1_1.webp','producto1_2.webp','producto1_3.webp','producto1_4.webp',true,true,89990),
(1,'Mancuernas Ajustables 2x24 kg','Sistema de ajuste rapido de peso.',15,'producto',
'producto2_1.webp','producto2_2.webp','producto2_3.webp','producto2_4.webp',true,true,299990),
(1,'Barra Olimpica 20 kg','Barra para powerlifting y halterofilia.',15,'producto',
'producto3_1.webp','producto3_2.webp','producto3_3.webp','producto3_4.webp',false,true,109990),
(1,'Discos Bumper 150 kg','Juego completo de discos de caucho.',12,'producto',
'producto4_1.webp','producto4_2.webp','producto4_3.webp','producto4_4.webp',true,true,399990),
(1,'Kettlebell Competicion 24 kg','Kettlebell profesional para cross-training.',20,'producto',
'producto5_1.webp','producto5_2.webp','producto5_3.webp','producto5_4.webp',false,true,59990),
(1,'Power Rack 2.5x2 m','Jaula de potencia multifuncional.',10,'producto',
'producto6_1.webp','producto6_2.webp','producto6_3.webp','producto6_4.webp',true,true,499990),
(1,'Banco Ajustable Comercial','Banco multiposicion de acero reforzado.',15,'producto',
'producto7_1.webp','producto7_2.webp','producto7_3.webp','producto7_4.webp',false,true,129990),
(1,'Rack para Mancuernas 3 Niveles','Soporte para 12 pares de mancuernas.',8,'producto',
'producto8_1.webp','producto8_2.webp','producto8_3.webp','producto8_4.webp',true,true,159990),
(1,'Maquina Polea Dual','Poleas ajustables para multiples ejercicios.',7,'producto',
'producto9_1.webp','producto9_2.webp','producto9_3.webp','producto9_4.webp',true,true,799990),
(1,'Prensa de Piernas 45 grados','Maquina profesional para tren inferior.',5,'producto',
'producto10_1.webp','producto10_2.webp','producto10_3.webp','producto10_4.webp',true,true,999990),
(1,'Cuerda de Batalla 12 m','Battle rope de uso intensivo.',20,'producto',
'producto11_1.webp','producto11_2.webp','producto11_3.webp','producto11_4.webp',false,true,59990),
(1,'Balon Medicinal 10 kg','Balon de caucho solido para lanzamientos.',25,'producto',
'producto12_1.webp','producto12_2.webp','producto12_3.webp','producto12_4.webp',false,true,34990),
(1,'Esterilla Antideslizante 10 mm','Colchoneta premium para entrenamientos.',30,'producto',
'producto13_1.webp','producto13_2.webp','producto13_3.webp','producto13_4.webp',true,true,19990),
(1,'Maquina Remo Sentado','Equipo con polea baja para dorsal y espalda.',6,'producto',
'producto14_1.webp','producto14_2.webp','producto14_3.webp','producto14_4.webp',true,true,849990),
(1,'Soga para Escalada 5 m','Cuerda de escalada para fuerza de agarre.',15,'producto',
'producto15_1.webp','producto15_2.webp','producto15_3.webp','producto15_4.webp',false,true,44990),
(1,'Paralelas de Fondo','Barras para dips y calistenia.',20,'producto',
'producto16_1.webp','producto16_2.webp','producto16_3.webp','producto16_4.webp',true,true,79990),
(1,'Maquina Smith','Estructura guiada para levantamientos seguros.',5,'producto',
'producto17_1.webp','producto17_2.webp','producto17_3.webp','producto17_4.webp',true,true,899990),
(1,'Soga de Velocidad','Cuerda ligera para entrenamiento cardiovascular.',35,'producto',
'producto18_1.webp','producto18_2.webp','producto18_3.webp','producto18_4.webp',false,true,9990),
(1,'TRX Pro Kit','Sistema de suspension para entrenamiento funcional.',15,'producto',
'producto19_1.webp','producto19_2.webp','producto19_3.webp','producto19_4.webp',true,true,59990),
(1,'Maquina Peck Deck','Equipo para pectorales y deltoides.',5,'producto',
'producto20_1.webp','producto20_2.webp','producto20_3.webp','producto20_4.webp',true,true,759990);

INSERT INTO productos (id_admin, titulo, descripcion, stock, tipo,
url_imagen, url_imagen2, url_imagen3, url_imagen4, destacado, activo, precio) VALUES
(1,'Instalacion de Power Rack','Montaje, nivelacion y anclaje de jaula de potencia.',NULL,'servicio',
'servicio1_1.webp','servicio1_2.webp','servicio1_3.webp','servicio1_4.webp',true,true,119990),
(1,'Mantenimiento Preventivo de Maquinas','Ajuste, limpieza y lubricacion de equipos de fuerza y cardio.',NULL,'servicio',
'servicio2_1.webp','servicio2_2.webp','servicio2_3.webp','servicio2_4.webp',true,true,89990),
(1,'Armado de Home Gym','Planificacion del espacio y montaje de equipo basico.',NULL,'servicio',
'servicio3_1.webp','servicio3_2.webp','servicio3_3.webp','servicio3_4.webp',true,true,159990),
(1,'Coaching Personal 1:1 (60 min)','Sesion personalizada de fuerza o hipertrofia.',NULL,'servicio',
'servicio4_1.webp','servicio4_2.webp','servicio4_3.webp','servicio4_4.webp',false,true,34990),
(1,'Plan Nutricional Deportivo','Plan personalizado orientado a rendimiento y composicion.',NULL,'servicio',
'servicio5_1.webp','servicio5_2.webp','servicio5_3.webp','servicio5_4.webp',false,true,39990),
(1,'Evaluacion Fisica y Test de Fuerza','Mediciones, RM estimada y movilidad base.',NULL,'servicio',
'servicio6_1.webp','servicio6_2.webp','servicio6_3.webp','servicio6_4.webp',false,true,29990),
(1,'Clinica de Powerlifting (3 h)','Tecnica de sentadilla, banca y peso muerto.',NULL,'servicio',
'servicio7_1.webp','servicio7_2.webp','servicio7_3.webp','servicio7_4.webp',true,true,89990),
(1,'Taller de Halterofilia (3 h)','Arranque y envion: progresiones y seguridad.',NULL,'servicio',
'servicio8_1.webp','servicio8_2.webp','servicio8_3.webp','servicio8_4.webp',true,true,99990),
(1,'Entrenamiento Funcional Grupal (hasta 10)','Circuitos full body con implementos.',NULL,'servicio',
'servicio9_1.webp','servicio9_2.webp','servicio9_3.webp','servicio9_4.webp',false,true,69990),
(1,'Mobility y Stretching (60 min)','Sesion guiada para movilidad y descarga.',NULL,'servicio',
'servicio10_1.webp','servicio10_2.webp','servicio10_3.webp','servicio10_4.webp',false,true,24990),
(1,'Programacion de Entrenamiento (4 sem)','Plan escrito con progresiones y seguimiento.',NULL,'servicio',
'servicio11_1.webp','servicio11_2.webp','servicio11_3.webp','servicio11_4.webp',true,true,44990),
(1,'Traslado y Montaje de Equipos','Retiro, transporte y reinstalacion segura.',NULL,'servicio',
'servicio12_1.webp','servicio12_2.webp','servicio12_3.webp','servicio12_4.webp',false,true,129990),
(1,'Ajuste y Lubricacion de Maquinas','Elimina ruidos, calibra cables y guias.',NULL,'servicio',
'servicio13_1.webp','servicio13_2.webp','servicio13_3.webp','servicio13_4.webp',false,true,49990),
(1,'Clinica de Kettlebells (2 h)','Tecnica segura de swing, clean y press.',NULL,'servicio',
'servicio14_1.webp','servicio14_2.webp','servicio14_3.webp','servicio14_4.webp',false,true,54990),
(1,'Recuperacion con Foam Roller (45 min)','Liberacion miofascial guiada.',NULL,'servicio',
'servicio15_1.webp','servicio15_2.webp','servicio15_3.webp','servicio15_4.webp',false,true,19990),
(1,'HIIT Corporativo On Site (60 min)','Clase intensa para equipos de empresa.',NULL,'servicio',
'servicio16_1.webp','servicio16_2.webp','servicio16_3.webp','servicio16_4.webp',true,true,119990),
(1,'Arriendo Jaula Barra Discos (por dia)','Set completo para eventos o sesiones puntuales.',NULL,'servicio',
'servicio17_1.webp','servicio17_2.webp','servicio17_3.webp','servicio17_4.webp',true,true,149990),
(1,'Workshop Ergonomia en Oficina','Prevencion de lesiones y pausas activas.',NULL,'servicio',
'servicio18_1.webp','servicio18_2.webp','servicio18_3.webp','servicio18_4.webp',false,true,99990),
(1,'Armado y Anclaje de Barra Dominadas','Instalacion en muro o techo con refuerzos.',NULL,'servicio',
'servicio19_1.webp','servicio19_2.webp','servicio19_3.webp','servicio19_4.webp',false,true,69990),
(1,'Sanitizacion de Equipos','Desinfeccion profunda grado profesional.',NULL,'servicio',
'servicio20_1.webp','servicio20_2.webp','servicio20_3.webp','servicio20_4.webp',false,true,39990);

INSERT INTO productos (
  id_admin, titulo, descripcion, stock, tipo, categoria,
  url_imagen, url_imagen2, destacado, activo, precio
) VALUES
(1,'Gold Standard 100% Whey Protein (5 Lb) - Original',
'Mezcla de proteina aislada, concentrada e hidrolizada de suero, con 24 g de proteina y 5.5 g de BCAA por porcion. Fuente de calcio y bajo en sodio.',
20,'producto','suplementos','producto21_1.webp','producto21_2.webp',true,true,90990),
(1,'Prostar Whey Protein (5 Lb) - Original',
'Proteina de suero con 25 g de proteina, 5 g de carbohidratos y 1 g de grasa por porcion. Favorece recuperacion y proteccion muscular.',
20,'producto','suplementos','producto22_1.webp','producto22_2.webp',true,true,70540),
(1,'Whey Pro Win (4.4 lb)',
'Suplemento con alto contenido de proteinas y aminoacidos para energia, recuperacion y desarrollo muscular.',
20,'producto','suplementos','producto23_1.webp','producto23_2.webp',true,true,87520),
(1,'Nutrex Creatina Monohidratada 400 gr',
'Creatina pura de rapida absorcion, 5 g por porcion. Mejora fuerza, potencia, resistencia y recuperacion.',
20,'producto','suplementos','producto24_1.webp','producto24_2.webp',true,true,22740),
(1,'Ultimate Nutrition Creatina Monohidratada 300 gr',
'Creatina micronizada para mejor absorcion. Aumenta volumen celular, fuerza y recuperacion muscular.',
20,'producto','suplementos','producto25_1.webp','producto25_2.webp',true,true,20990),
(1,'Optimum Nutrition Creatina Powder 300 gr',
'Creatina monohidratada en polvo de alta pureza. Regenera ATP e incrementa fuerza y potencia.',
20,'producto','suplementos','producto26_1.webp','producto26_2.webp',true,true,35990),
(1,'Lipo 6 Intense Ultra Concentrate 60 Caps Nutrex',
'Termogenico con cafeina, te verde, vitaminas D, B6, B12, cromo y yodo. Aporta energia y apoyo metabolico.',
20,'producto','suplementos','producto27_1.webp','producto27_2.webp',true,true,22950),
(1,'Caffeine 200 Energia (60 caps) - Original',
'Capsulas de cafeina (210 mg cada una) para energia rapida y concentracion.',
20,'producto','suplementos','producto28_1.webp','producto28_2.webp',true,true,19990),
(1,'Kreator Blue Aggression 600 gr',
'Pre-entreno disenado para mejorar energia, fuerza y rendimiento en sesiones intensas.',
20,'producto','suplementos','producto29_1.webp','producto29_2.webp',true,true,34990),
(1,'Solgar L-Glutamina 60 tabletas',
'Glutamina para apoyar recuperacion muscular, reducir dolor y conservar masa magra.',
20,'producto','suplementos','producto30_1.webp','producto30_2.webp',true,true,24990),
(1,'Optimum Nutrition Glutamina Powder 300 gr',
'Glutamina que acelera recuperacion y reconstruccion de tejidos musculares.',
20,'producto','suplementos','producto31_1.webp','producto31_2.webp',true,true,34990),
(1,'Glutamine Drive 300 gr - Original',
'L-Glutamina pura sin sabor. Favorece reparacion muscular y crecimiento.',
20,'producto','suplementos','producto32_1.webp','producto32_2.webp',true,true,32990),
(1,'E-Amino 2200 (120 soft) - Original',
'Formula con 18 aminoacidos y L-carnitina para potenciar recuperacion muscular.',
20,'producto','suplementos','producto33_1.webp','producto33_2.webp',true,true,26990),
(1,'Amino 2222 (320 Tabs) - Original',
'Mezcla de aminoacidos esenciales y no esenciales para mantener niveles constantes y favorecer recuperacion.',
20,'producto','suplementos','producto34_1.webp','producto34_2.webp',true,true,50990),
(1,'Aminoxine Plus (60 caps)',
'Aminoacidos con zinc que apoyan la sintesis de proteinas, colageno y queratina.',
20,'producto','suplementos','producto35_1.webp','producto35_2.webp',true,true,14990),
(1,'Amino 2002 (100 Tabs) - Original',
'Formula de aminoacidos esenciales y no esenciales que ayuda a conservar masa muscular.',
20,'producto','suplementos','producto36_1.webp','producto36_2.webp',true,true,29990),
(1,'Quest Barra Proteica (60 gr)',
'Barra con 20-21 g de proteina, rica en fibra y calcio. Ideal como snack.',
20,'producto','suplementos','producto37_1.webp','producto37_2.webp',true,true,3670),
(1,'Twentys Snack Proteico (60 gr)',
'Barra nutritiva con proteina y buen perfil nutricional.',
20,'producto','suplementos','producto38_1.webp','producto38_2.webp',true,true,3090),
(1,'Wild Protein Chocolate Mani (45 gr)',
'Barra crocante con proteina de soya y suero de leche, sin azucar.',
20,'producto','suplementos','producto39_1.webp','producto39_2.webp',true,true,1890),
(1,'Barra Proteica Protein Bite Ygoal',
'Barra en tres capas: chocolate, caramelo y cobertura de chocolate blanco con crispis.',
20,'producto','suplementos','producto40_1.webp','producto40_2.webp',true,true,2790);


SELECT COUNT(*) FROM productos;
